// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAS.Calculation.Infrastructure.Persistence;

#nullable disable

namespace PAS.Calculation.Infrastructure.Migrations
{
    [DbContext(typeof(CalculationDbContext))]
    [Migration("20260721061203_AddProcessMessages")]
    partial class AddProcessMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("calculation")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAS.Calculation.Domain.FundPerformances.FundPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FundPerformances", "calculation");
                });

            modelBuilder.Entity("PAS.Calculation.Infrastructure.Persistence.Inbox.ProcessedMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EventId");

                    b.ToTable("ProcessedMessages", "calculation");
                });

            modelBuilder.Entity("PAS.Calculation.Domain.FundPerformances.FundPerformance", b =>
                {
                    b.OwnsMany("PAS.Calculation.Domain.FundPerformances.NavPoint", "Navs", b1 =>
                        {
                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("FundId", "Date");

                            b1.ToTable("NavPoints", "calculation");

                            b1.WithOwner()
                                .HasForeignKey("FundId");
                        });

                    b.Navigation("Navs");
                });
#pragma warning restore 612, 618
        }
    }
}
